plugins {
    id 'application'
}

repositories { mavenCentral() }

dependencies {
    implementation 'org.postgresql:postgresql:42.7.5'
    implementation 'org.json:json:20240303'
}

application { mainClass = 'za.co.smartpantry.api.Server' }

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
